### ISSUE TITLE
UnsatisfiedDependencyException

### ISSUE THREAD

**Issue by Rama-Sundaram** [hendisantika/user-management-app#10]
Hi Hendisantika,

While trying to compile the program using Maven command always getting below exception. Please help to solve this issue

_2022-07-11 11:07:54.299  WARN 15011 --- [           main] o.s.w.c.s.GenericWebApplicationContext   : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'initialSetup': Unsatisfied dependency expressed through field 'userService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userService': Unsatisfied dependency expressed through field 'bCryptPasswordEncoder'; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'securityConfiguration': Requested bean is currently in creation: Is there an unresolvable circular reference?
2022-07-11 11:07:54.300  INFO 15011 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2022-07-11 11:07:54.301  INFO 15011 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2022-07-11 11:07:54.306  INFO 15011 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2022-07-11 11:07:54.316  INFO 15011 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-07-11 11:07:54.349 ERROR 15011 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'initialSetup': Unsatisfied dependency expressed through field 'userService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userService': Unsatisfied dependency expressed through field 'bCryptPasswordEncoder'; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'securityConfiguration': Requested bean is currently in creation: Is there an unresolvable circular reference?_

**Comment by hendisantika** [comment]
Hi @Rama-Sundaram , can you pull the latest code?

Let me know if it's still failing.

Thanks

**Comment by Rama-Sundaram** [comment]
Hi @hendisantika ,

Could see still the application failed to load due to connection error,

Test set: com.hendisantika.usermanagementapp.UserManagementAppApplicationTests
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.438 s <<< FAILURE! - in com.hendisantika.usermanagementapp.UserManagementAppApplicationTests
contextLoads  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: org/springframework/boot/ApplicationContextFactory
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.ApplicationContextFactory


Thanks,
Ram

**Comment by hendisantika** [comment]
Have you pulled the latest code? It was OK on my local

**Comment by Rama-Sundaram** [comment]
Hi @hendisantika ,

Yes, have downloaded the latest code from Master, while debugging found below exception while initialising mysql connection 

2022-07-21 11:01:04.145 ERROR 91388 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Exception during pool initialization.

com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.29.jar:8.0.29]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.29.jar:8.0.29]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.29.jar:8.0.29]

**Comment by hendisantika** [comment]
When that error comes?

Skip the test

**Comment by Rama-Sundaram** [comment]
Hi @hendisantika ,

Im getting this error on compilation. Have verified the mysql library in maven and could see it was present. But still getting the connection error,

Attached the full error logs.

[UserManagementAppApplication.txt](https://github.com/hendisantika/user-management-app/files/9158751/UserManagementAppApplication.txt)

**Comment by hendisantika** [comment]
Please click the link s.id/hndi to fix this issue.

**Comment by Rama-Sundaram** [comment]
Thanks for all your help @hendisantika .
Finally it worked..
You are great!

**Comment by hendisantika** [comment]
You are welcome.
